### PR TITLE
fix: dim would not get applied when lazy loading plugin

### LINKED ISSUE #26: The dim setting doesn't work when the plugin is lazy-loaded
Here's my lazy.nvim config:

```lua
return {
    'okuuva/auto-save.nvim',
    event = 'BufRead',

    opts = {
        execution_message = {
            dim = 0.4,
            cleaning_interval = 1000
        }
    }
}
```

The value of the dim setting doesn't work. This is because it's only read when `VimEnter`, `ColorScheme` or `UIEnter` is triggered:
https://github.com/okuuva/auto-save.nvim/blob/19bd29c150274e3283ea28d88600e40d14c28803/lua/auto-save/init.lua#L151

Since I'm loading the plugin at `BufRead`, this happens after any of these events (unless I manually change the colorscheme later).

Also, I can't manually set the `AutoSaveText` highlight as a workaround, because that's only configured when `dim` is read.

### PR DESCRIPTION
**Pull request by primeapple**
Fixes #26

- Dim is now getting applied when plugin is turned on, as well as when the colorscheme is changed
- Only apply dim if execution message is enabled
- Moved the color logic out of `init.lua`, into `colors.lua`
- Added some types

### CODE REVIEW

File: lua/auto-save/init.lua [hunk 1]
```diff
@@ -148,32 +148,18 @@ function M.on()
...
-        end
+  local function dim()
+    if cnf.opts.execution_message.enabled then
+      schedule(function()
+        colors.apply_colors(cnf.opts.execution_message.dim)
       end)
+    end
+  end
+
+  dim()
```
Comment (okuuva) [inline lua/auto-save/init.lua:159]: I think this should be called `setup_dimming` or `config_dimming` or something like that since it's not actually dimming anything at call time.

File: lua/auto-save/utils/colors.lua [hunk 2]
```diff
@@ -44,27 +56,42 @@ function M.get_hl(name)
...
 
-function M.darken(hex, amount, bg)
-  return M.blend(hex, bg or M.bg, math.abs(amount))
+--- @param dim_value number
+M.apply_colors = function(dim_value)
+    if dim_value > 0 then
+      MSG_AREA = get_hl("MsgArea")
+      if MSG_AREA.foreground ~= nil then
+        MSG_AREA.background = (MSG_AREA.background or get_hl("Normal")["background"])
+        -- TODO maybe there is a hiccup here, test a bit
```
Comment (okuuva) [inline lua/auto-save/utils/colors.lua:80]: Is this TODO still relevant?

**Review by okuuva — CHANGES_REQUESTED** [review]
Just one comment about naming and an added TODO. Great work once again, thanks!

File: lua/auto-save/utils/colors.lua (hunk 2 above)
Comment (primeapple) [reply lua/auto-save/utils/colors.lua]: I don't understand what the original author did here. In my opinion the naming of the variables is incorrect, we are somewhere mixing up foreground and background. Here or in the `blend` function.

But it works, so I don't want to touch it further ;-)

Comment (okuuva) [reply lua/auto-save/utils/colors.lua]: Fair enough. TBH I'm not sure if dimming should be even implemented here, it should be the responsibility of some UI plugin. IMO we should deprecate it and come up with a bit more general solution.

Up to you if you want to update the TODO with a bit more details or even a deprecation notice.

**Review by okuuva — APPROVED** [review]
LGTM!

**Comment by primeapple** [comment]
I added comments to describe the legacy nature of this code.

You can merge now.

Btw, can you give me write access? I promise I won't merge anything without an approval, but it would be nice nethertheless ;-)

**Comment by okuuva** [comment]
> Btw, can you give me write access? I promise I won't merge anything without an approval, but it would be nice nethertheless ;-)

I can and will :) I really appreciate your efforts on making auto-save.nvim better, thank you! I'll set it up shortly.

**Comment by okuuva** [comment]
> I added comments to describe the legacy nature of this code.
> 
> You can merge now.

Thank you for the edits! You should be able to merge this now yourself :)
